name: sw_fun_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^5.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  json_annotation: ^4.7.0
  dio: ^4.0.6
  flutter_screenutil: ^5.5.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.4.1

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: NouvelRegular
      fonts:
        - asset: assets/fonts/NouvelR-Regular.ttf
    - family: NouvelLight
      fonts:
        - asset: assets/fonts/NouvelR-Light.ttf
    - family: NouvelBook
      fonts:
        - asset: assets/fonts/NouvelR-Book.ttf
    - family: NouvelBold
      fonts:
        - asset: assets/fonts/NouvelR-Bold.ttf
    - family: NouvelSemibold
      fonts:
        - asset: assets/fonts/NouvelR-Semibold.ttf
    - family: NouvelExtrabold
      fonts:
        - asset: assets/fonts/NouvelR-Extrabold.ttf